### PR TITLE
interpolate values into include files

### LINKED ISSUE #165: Allow included files to be templated
## What happened?

* What were you attempting to do?
I was trying to include some templated values like `{{port}}` in a file that I was `include`-ing in my `nginx.conf`. When my app starts the included file has not be templated and NGINX fails to start.

* What did you expect to happen?
I expected that my templated files were generated with the dynamic values they require.

## Build Configuration

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

### `nginx.conf`
```
worker_processes 1;
include my-file.conf;
```

### `my-file.conf`
```
http {
  charset utf-8;
  log_format cloudfoundry 'NginxLog "$request" $status $body_bytes_sent';
  access_log /dev/stdout cloudfoundry;
  default_type application/octet-stream;
  include mime.types;
  sendfile on;

  tcp_nopush on;
  keepalive_timeout 30;
  port_in_redirect off; # Ensure that redirects don't include the internal container PORT - 8080

  server {
    listen {{port}};
    root public;
    index index.html index.htm Default.htm;
  }
}
```

## Checklist
* [x] I have included steps for reproduction.

### PR DESCRIPTION
**Pull request by fg-j**
Resolves #165

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [x] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [x] I have added an integration test, if necessary.
* [x] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.

### CODE REVIEW

**Comment by fg-j** [comment]
Still to do: support file masks like `include /home/*.conf`

File: cmd/configure/main.go [hunk 1]
```diff
@@ -3,49 +3,87 @@ package main
...
+
+		if err := tmpl.ExecuteTemplate(file, filepath.Base(conf), nil); err != nil {
+			log.Fatalf("failed to execute template: %s", err)
+		}
+	}
+}
+
+func getIncludedConfs(confText string, confDir string) ([]string, error) {
+	includeFiles := []string{}
+	includeRe := regexp.MustCompile(`include (\S*.conf);`)
```
Comment (arjun024) [inline cmd/configure/main.go:72]:
```suggestion
	includeRe := regexp.MustCompile(`include\s+(\S*.conf);`)
```
Nginx is still happy with multiple whitespace between directive and param

**Review by arjun024 — CHANGES_REQUESTED** [review]
Except a tiny requested change, looks pretty good to me

**Review by arjun024 — APPROVED** [review]
